name: Update Flight Data
on:
  schedule:
    - cron: '0 * * * *' # 매 정각(UTC 기준)마다 실행
  workflow_dispatch: # 수동으로 실행해볼 수 있는 버튼 생성

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install FlightRadarAPI beautifulsoup4
      - name: Run Scraper
        run: python scraper.py
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data.js
          git commit -m "Auto update flight data" || exit 0
          git push
